---

- name: create a login token
  uri: 
    url: "{{ act_api_login }}" 
    validate_certs: no  
  register: logintoken 

- name: list registered vcenters
  uri: 
    url: "{{ act_api_info }}/lshost?filtervalue=hosttype=vcenter&sessionid={{ logintoken.json.sessionid}}"
    validate_certs: no
  register: lshost

- name: discover clusters 
  uri:
    url: "{{ act_api_task }}/vmdiscovery?discoverclusters&host={{ item.id }}&sessionid={{ logintoken.json.sessionid}}"
    validate_certs: no
    method: POST
  register: vmdiscovery
  with_items: "{{ lshost.json.result }}"

- name: discover vms
  uri:
    url: "{{ act_api_task }}/vmdiscovery?discovervms&host={{ item.item.id }}&cluster={{ item.json.result[0].name }}&sessionid={{ logintoken.json.sessionid}}"
    validate_certs: no
    method: POST
  register: vmdiscovery_vms
  with_items: "{{ vmdiscovery.results }}"

- name: add the vms to the appliance
  uri:
    url: "{{ act_api_task }}/vmdiscovery?addvms&host={{ item.0.item.item.id }}&cluster={{ item.0.item.json.result[0].name }}&vms={{ item.1.vmname }}&sessionid={{ logintoken.json.sessionid}}"
    validate_certs: no
    method: POST
  when: item.1.ipaddress == "{{ ansible_host }}"
  with_subelements: 
    - "{{ vmdiscovery_vms.results }}"
    - json.result

