---
# tasks file for actifio_agent

- name: generate authentication token
  uri:
    url: "{{ act_api_login }}"
    validate_certs: no  
  register: logintoken

- name: session id is a fact
  set_fact: 
    act_sessionid: "{{ logintoken.json.sessionid }}"

- include: agent_redhat.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "RedHat"

- include: discover_vm.yml
  when: discover_as_vm == true

- include: add_host_iscsi.yml
  when: not discover_as_vm 

- include: discover_apps.yml
  when: discover_apps == true
